### PR TITLE
WP-5563 Setup Travis CI

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Changes

- Setup Travis CI (and update smithy to minimal config)
- Fix the library directive name in `src/js_interop.dart`

## Testing

- [ ] CI passes (includes Travis CI, Smithy, and Codecov)

## Code Review
@Workiva/app-frameworks

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by rm-astro-wf** [comment]
Sorry, I could not create a JIRA ticket for this pull.

I sent the following data to JIRA:
`{'issuetype': {'name': 'Task'}, 'project': {'key': u'WP'}, 'description': '## Changes\r\n\r\n- Setup Travis CI (and update smithy to minimal config)\r\n- Fix the library directive name in `src/js_interop.dart`\r\n\r\n## Testing\r\n\r\n- [ ] CI passes (includes Travis CI, Smithy, and Codecov)\r\n\r\n## Code Review\r\n@Workiva/app-frameworks ', 'components': [], 'summary': 'Setup Travis CI'}`

I received the following data from JIRA:
`Hidden on Open Source Repos`

If this is an issue that you cannot resolve, please reach out to RM in the Release Management chat room.

**Comment by maxwellpeterson-wf** [comment]
+10
- Travis CI passes
- Smithy passes

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
  - Documented [here](https://github.com/Workiva/sockjs_client_wrapper/pull/5#issuecomment-350774622)
- [ ] Tests created/updated 
- [x] All tests pass

@Workiva/release-management-pp

**Comment by jayudey-wf** [comment]
investigating codecov item

**Pull request closed without merging**
