### PR TITLE
FEA-1212 Update SockJS to v1.6.1

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Motivation
There are a few CVEs that have been addressed in the latest sockjs-client releases.

## Changes
Updates the version of sockjs-client bundled with this Dart wrapper from 1.5.0 to 1.6.1.

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched file <code>lib/sockjs.js</code> modified</li>
<li>Watched file <code>lib/sockjs_prod.js</code> modified</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by matthewnitschke-wk — DISMISSED** [review]
Is there a reason we're not committing a `package.json` file in this repo? it would be nice to establish a common pattern for dependency updates, and maybe even run it in CI?

**Comment by evanweible-wf** [comment]
No reason other than we haven't had to do it often. Agreed that it would be nice to automate this process!

**Comment by autobot-wf** [comment]
Skynet test results failed initially for this build but were approved by evan.weible
https://wf-skynet-hrd.appspot.com/apps/test/smithy/4197265/1
Approval message: Failure on beta channel is likely due to outdated dependencies, will address separately

**Comment by evanweible-wf** [comment]
QA +1
- [x] Tested this with our main application, all CI passes.

**Review by corwinsheahan-wf — APPROVED** [review]

**Comment by corwinsheahan-wf** [comment]
security +1
* Updates assets to 1.6.1 from [here](https://github.com/sockjs/sockjs-client/tree/v1.6.1/dist), which remediates several CVEs in the current version we're using.

**Comment by evanweible-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
