### PR TITLE
Update SockJS version, switch to Github Actions for CI

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Motivation
There's some ongoing investigation into websocket fallbacks, and we'd like to upgrade to the latest version of the SockJS library to pull in any fixes that might be helpful.

## Changes
- Currently this package wraps SockJS v1.1.5. This PR upgrades to SockJS v1.5.0. (see diff here: https://github.com/sockjs/sockjs-client/compare/v1.1.5...v1.5.0)
- Additionally:
  - Use workiva_analysis_options
  - Switch from Travis CI to Github Actions

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched file <code>lib/sockjs.js</code> modified</li>
<li>Watched file <code>lib/sockjs_prod.js</code> modified</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/teams/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by todbachman-wf — APPROVED** [review]

**Review by brianshannan-wf — APPROVED** [review]

**Comment by brianshannan-wf** [comment]
Security +1
- After removing indentation differences, the sockjs and minified sockjs code is identical to the published sockjs code

**Comment by brianshannan-wf** [comment]
QA +1
- Was able to successfully create a websocket to talk to the messaging-frontend deployed in wk-dev
- Was able to use xhr-streaming as a fallback to talk to the messaging-frontend deployed in wk-dev, after some alterations to allow the set-cookie directive from nginx to work on localhost. This wouldn't be necessary in a deployed environment as the cookie wouldn't be cross-origin.

**Comment by brianshannan-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
