### PR TITLE
RM-188731 Release sockjs_client_wrapper 1.3.0

### PR DESCRIPTION
**Pull request by rmconsole-readonly-wk**
Pull Requests included in release:
* Minor changes:
	* [FEA-2863: Expose debug transport URL when possible](https://github.com/Workiva/sockjs_client_wrapper/pull/64)
* Patch changes:
	* [Dart 2.19](https://github.com/Workiva/sockjs_client_wrapper/pull/63)

Requested by: @evanweible-wf

Diff Between Last Tag and Proposed Release: https://github.com/Workiva/sockjs_client_wrapper/compare/1.2.0...Workiva:release_sockjs_client_wrapper_1.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/sockjs_client_wrapper/compare/1.2.0...1.3.0

The logs for the request that created this PR can be found [here](https://w-rmconsole.appspot.com/release/release_event/4523073540194304/logs/)
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4523073540194304/?repo_name=Workiva%2Fsockjs_client_wrapper&pull_number=65)

### CODE REVIEW

**Review by evanweible-wf — APPROVED** [review]

**Comment by evanweible-wf** [comment]
QA +1 @Workiva/release-management-p

**Review by matthewnitschke-wk — APPROVED** [review]

**Comment by corwinsheahan-wf** [comment]
@Workiva/release-management-p

**Review by corwinsheahan-wf — APPROVED** [review]

**Comment by corwinsheahan-wf** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
