### PR TITLE
WP-6463 Update to SockJS v1.1.5

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Description
SockJS v1.1.5 includes a fix that prevents the xhr_streaming protocol from getting stuck in an infinite loop of sending requests to the xhr_streaming endpoint.

## Testing
- [ ] CI passes

## Code Review
@Workiva/app-frameworks 
fyi: @tylerrinnan-wf

### CODE REVIEW

**Comment by aviary3-wk** [comment]
## Security Insights
The items listed below may not capture all security relevant changes. Before providing a security review, be sure to review the entire PR for security impact.
<details>
<summary>(2) Security relevant changes were detected</summary>
<li>Watched file <code>lib/sockjs.js</code> modified</li>
<li>Watched file <code>lib/sockjs_prod.js</code> modified</li>
</details>

## Action Items
* Obtain a [security review](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); reviewer should pay special attention to insights listed above
* Verify [`aviary.yaml`](https://dev.workiva.net/docs/information-security/aviary#configuring-aviary) coverage of security relevant code
---
_Questions or Comments? Reach out on HipChat: InfoSec Forum._

**Comment by toddbeckman-wf** [comment]
Security +1

- [x] Assets are the same as on https://cdnjs.com/libraries/sockjs-client/1.1.5 except for the sourcemap comment on the end.

**Comment by maxwellpeterson-wf** [comment]
+10
- CI passes

**Comment by maxwellpeterson-wf** [comment]
QA +1
- [x] Dev +1's
- [x] Dev/QA +10 with detail of what was tested
  - https://github.com/Workiva/sockjs_client_wrapper/pull/12#issuecomment-401917436
- [ ] Tests created/updated 
  - Not necessary for these changes
- [x] All tests pass

@Workiva/release-management-pp

**Pull request merged**
