### PR TITLE
WP-5563 Setup Travis CI (attempt #2)

### PR DESCRIPTION
**Pull request by evanweible-wf**
## Changes

- Setup Travis CI (and update smithy to minimal config)
- Fix the library directive name in `src/js_interop.dart`

## Testing

- [ ] CI passes (includes Travis CI, Smithy, and Codecov)

## Code Review
@Workiva/app-frameworks

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven
<details>
<summary>Number of Findings: 0</summary>

</details>

**Comment by jayudey-wf** [comment]
previously reviewed here

**Comment by jayudey-wf** [comment]
QA +1

- [ ] Testing instruction
- [ ] Dev +1's
- [ ] Dev/QA +10 with detail of what was tested
  - passing CI (pending issue with codecov)
- [ ] Security review (if required)
- [ ] Unit tests created/updated
- [ ] All unit tests pass
- [ ] Rosie has run and reports properly the release the ticket will be included in
- [ ] Areas of regression noted

Merging into master.

**Comment by jayudey-wf** [comment]
@Workiva/release-management-pp

**Pull request merged**
