### PR TITLE
Fix CI: Disable beta channel in CI since it's Dart 3.0

### PR DESCRIPTION
**Pull request by timothysteward-wk**
## Motivation
  
This package does not support Dart 3 because it has not been migrated to null safety.

Previously the dev channel was on Dart 3 and the beta channel was on Dart 2.19. We were able to build fine with the beta channel because it was still on Dart 2.19. Now both the dev and beta channels are on Dart 3, so building with the beta channel no longer works.

The beta channel CI check is now broken. The PR comments it out. Once we get the package migrated to null safety we can reenable it.

## Review
_[See CONTRIBUTING.md][contributing-review-types] for more details on review types (+1 / QA +1 / +10) and code review process._

  

Please review: 

### QA Checklist
- [ ] Tests were updated and provide good coverage of the changeset and other affected code
- [ ] Manual testing was performed if needed
    - [ ] Steps from PR author: 
        
    - [ ] Anything falling under manual testing criteria [outlined in CONTRIBUTING.md][contributing-manual-testing]

## Merge Checklist
While we perform many automated checks before auto-merging, some manual checks are needed:
- [ ] A Frontend Architecture member has reviewed these changes
- [ ] There are no unaddressed comments _- this check can be automated if reviewers use the "Request Changes" feature_
- [ ] _For release PRs -_ Version metadata in Rosie comment is correct

[contributing-review-types]: https://github.com/Workiva/sockjs_client_wrapper/blob/master/CONTRIBUTING.md#review-types
[contributing-manual-testing]: https://github.com/Workiva/sockjs_client_wrapper/blob/master/CONTRIBUTING.md#manual-testing-criteria

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by kimlarson-wk — APPROVED** [review]

**Comment by kimlarson-wk** [comment]
QA+1 CI passing is sufficient

**Comment by kimlarson-wk** [comment]
@Workiva/release-management-pp ready for merge.

**Comment by kimlarson-wk** [comment]
Kick

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
